[package]
name = "ebdev-toolchain-binary"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
reqwest.workspace = true
futures-util.workspace = true
flate2.workspace = true
tar.workspace = true
xz2.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["full", "test-util"] }
